---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 140
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_paths:
- test/
- src/client/Snap--Build-Your-Own-Blocks/
