---
version: "3"
services:
  cloud:  # Basic account management, network overlay, etc
    restart: always
    image: netsblox/cloud:latest
    volumes:
        - ${PWD}/cloud/crates/cloud/config/default.toml:/config/default.toml
    ports:
        - "8080:8080"

  services:  # NetsBlox RPCs
    restart: always
    image: netsblox/services:latest
    ports:
        - "8081:8081"
    environment:
        - "NETSBLOX_CLOUD=http://cloud:8080"
        - "NETSBLOX_CLOUD_ID=NetsBloxServices"
        - "NETSBLOX_CLOUD_SECRET=PUT_SECRET_HERE"
        - "PORT=8081"
        - "MONGO_URI=mongodb://mongo:27017"

  browser:  # Hosts the client files
    restart: always
    image: netsblox/browser:latest
    ports:
        - "2000:2000"
    environment:
        - "CLOUD_URL=https://cloud.netsblox.org"
        - "PORT=2000"

  mongo:
    restart: always
    image: mongo:5.0-focal

# Blob storage for project contents (media, etc)
